### ISSUE TITLE
Udeler stopped working

### ISSUE THREAD

**Issue by Fran6jy** [FaisalUmair/udemy-downloader-gui#292]
As at today, Udeler has been unable to login Udemy and the app has been blank
Am I the only one experiencing this?

**Comment by mohfathy0** [comment]
No I am facing issues too 
on the old releases, it returns wrong password and on the latest just a blank pop-up whenever I focus on the web login window

**Comment by Fran6jy** [comment]
It has been fixed tho

**Comment by mohfathy0** [comment]
When? I just experienced it today and that why I am here

**Comment by FaisalUmair** [comment]
@mohfathy0  Are you still facing this issue?

**Comment by mohfathy0** [comment]
@FaisalUmair thanks it works but I liked the old authentication better than navigating to udemy  as I used to embed my account within the app and hide the text input before sharing it with friends

**Comment by UltimateManas** [comment]
I am still facing this issue. Enrolled courses are not being populated.

**Comment by baraanasser** [comment]
I can't log in to udemy using  Udeler at all < I tried many time but it not work >> it was working before but now I can't log in

**Comment by DE-HEUER** [comment]
as of today 3 april 2021, udeler cannot download udemy courses. mine only shows building downloading but never makes progress... Bye bye, udeler???

**Comment by DE-HEUER** [comment]
as of today 3 april 2021, udeler cannot download udemy courses. mine only shows building downloading but never makes progress... Bye bye, udeler??? Hellooooo Allavsoft!!

**Comment by mohfathy0** [comment]
@DE-HEUER  what is allavsoft ? and can you log in there with udemy account?

**Comment by DE-HEUER** [comment]
> @DE-HEUER what is allavsoft ? and can you log in there with udemy account?

it's a paid software but compared to udeler, udeler is much more advance that it can download all the courses at one time including the attachement. Not that case with Allavsoft even though there is a feature that allow you to download multiple videos by copy paste the links on its dialog box. Anyway, Udeler has been a very great help for me to download all the Udemy courses that I bought. Of course, I used the downloaded Udemy courses for my personal use only. I need to download them since Internet connection in my country is bad and not stable so by downloading I can play and replay the courses with more convenience. Thanks to Faisal Umair the creator of Udeler. You have been a great help fo me. If there is any chance for me to buy or subscribe your software, I would be happy to do that.

**Comment by DE-HEUER** [comment]
Yes, you need to login with your udemy email address and password.

**Comment by vijgarud** [comment]
iam unable to use udeler.whenever I use to login using my google account it says browser is not secure.I tried all the versions 

![image](https://user-images.githubusercontent.com/28746450/123379451-c075c680-d5ab-11eb-9437-d006027d7a1f.png)


![image](https://user-images.githubusercontent.com/28746450/123379507-dedbc200-d5ab-11eb-89ac-2979e37bb92e.png)
