### ISSUE TITLE
The application "Udeler" can't be opened (1.8.1) - Mac OSX

### ISSUE THREAD

**Issue by andrewboening** [FaisalUmair/udemy-downloader-gui#388]
Hey all,

Grabbed 1.8.1 today to try and resolve the attachment download issue. After unzipping and trying to run, I get the following error;
The application "Udeler" can't be opened

Have checked file permissions to make sure user has execute access. Cloned project from GIT and am able to run successfully using node. 

Have also compiled by using 'npm run build-mac'. Compile is successful and can install/run when using DMG. Appears to only be an issue when extracting from ZIP

**Operating System**: OSX Catalina 10.15.1

**Comment by muhelsaied** [comment]
Look like new Mac policy prevent app from running
Or there is aproblem in electron package
<img width="429" alt="75799014-1f447a80-5d80-11ea-96a8-d07e3b244d77" src="https://user-images.githubusercontent.com/42692713/75911293-05766680-5e58-11ea-9d06-a9dae6d7a754.png">

**Comment by iambenqazy** [comment]
Got the same issue on Mac OS 10.15.3 too

**Comment by jasonewillis** [comment]
+1

**Comment by cerebroo** [comment]
v1.8.0 is working fine on Mac. Issue is with v1.8.1

**Comment by Vinaypandeymobiquityinc** [comment]
<img width="587" alt="Screenshot 2020-03-05 at 11 59 57 AM" src="https://user-images.githubusercontent.com/59195535/75954088-d6eca000-5ed8-11ea-897d-f43637e889ad.png">
Unable to open the application, please refer the attached screen shot.

**Comment by andrewboening** [comment]
Did some more digging and it's possible that could be with the notirization of the app folder in the ZIP. Have cloned the project and am looking into to see if I can find root cause/solution. In the meantime, for those who are savvy, clone the GIT project, compile using npm run build-mac and use the DMG instead of the ZIP

**Comment by Montalvolll** [comment]
@andrewboening thanks pal, that worked for me. Using CatalinaOS 10.15.3.
For those who are not so techy follow this steps:

First navigate to your Desktop folder using the terminal.

Once you are there just clone the project using the following command.

`git clone https://github.com/FaisalUmair/udemy-downloader-gui.git`

next, navigate to the 'udemy-downloader-gui' folder on the terminal and use the following command

`npm install`

after this finish run the following command

`npm run build-mac`

wait until you see the prompt ready to use.

Finally just follow this route: desktop > udemy-downloader-gui > dist.
Right click on Udeler-1.8.1.dmg and click open.

**Comment by muhelsaied** [comment]
look like there is problem in electron compiler zip file give error 
as u mentioned dmg file and unzip file works

**Comment by Santhosh-Umapathi** [comment]
This doesnt work either, udeler starts when writing npm start on terminal. Cannot change download folder.

Once you are there just clone the project using the following command.

git clone https://github.com/FaisalUmair/udemy-downloader-gui.git

next, navigate to the 'udemy-downloader-gui' folder on the terminal and use the following command

npm install

after this finish run the following command

npm run build-mac

wait until you see the prompt ready to use.

Finally just follow this route: desktop > udemy-downloader-gui > dist.
Right click on Udeler-1.8.1.dmg and click open.

**Comment by FaisalUmair** [comment]
I have released v1.8.2 (which fixes the download path issue #390). Mac version of the new release comes in dmg. So that should work fine.

**Comment by Santhosh-Umapathi** [comment]
@FaisalUmair  Thanks for the new release v1.8.2 , works like charm !!

**Comment by infovinaypandey** [comment]
superb job

**Comment by mburakolgun** [comment]
I get an error in 1.8.2 for mac, videos are not downloading. Is there anyone who has experienced the same problem?

**Comment by hendurhance** [comment]
Still getting “Udeler” cannot be opened because the developer cannot be verified for M1. Any fix?
